
-- === Departments ===
CREATE TABLE IF NOT EXISTS public.departments (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO public.departments (name) VALUES
('Engineering'),
('Marketing'),
('Research'),
('Finance'),
('Operations');


-- === Types ===
CREATE TABLE IF NOT EXISTS public.types (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO public.types (name) VALUES
('Innovation'),
('Maintenance'),
('Optimization');


-- === Topics ===
CREATE TABLE IF NOT EXISTS public.topics (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    is_deleted BOOLEAN,
    department_id BIGINT NOT NULL,
    type_id BIGINT NOT NULL,
    existing_solutions VARCHAR(255) NOT NULL,
    goal VARCHAR(255) NOT NULL,
    keywords VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    problem_carrier VARCHAR(255) NOT NULL,
    CONSTRAINT fk_topic_department FOREIGN KEY (department_id) REFERENCES public.departments (id),
    CONSTRAINT fk_topic_type FOREIGN KEY (type_id) REFERENCES public.types (id)
);

-- === Sample Topic Records ===
INSERT INTO public.topics
(is_deleted, department_id, type_id, existing_solutions, goal, keywords, name, problem_carrier)
VALUES

(false, 1, 1, 'Agent every development.', 'Quality throughout beautiful instead.', 'ahead, despite, measure', 'Assimilated next generation customer loyalty', 'Santos, Gardner and Robinson'),
(false, 3, 1, 'Everything thank serve civil institution everyone.', 'Whatever from behavior benefit suggest.', 'page, southern, role', 'Public-key bottom-line implementation', 'Arnold Ltd'),
(false, 2, 1, 'Those gun court attorney product significant.', 'Talk term herself law.', 'street, class, great', 'Synchronized encompassing standardization', 'Wong, Lynch and Jackson'),
(false, 1, 3, 'Clear here writer policy.', 'Detail food shoulder argue start source husband.', 'at, tree, note', 'Universal foreground data-warehouse', 'Porter, Wilkerson and Day'),
(false, 5, 1, 'Enter east no.', 'Section investment on gun young.', 'catch, management, sense', 'Customizable coherent product', 'Conner Group'),
(false, 5, 2, 'As high you more wife team.', 'Quite boy those.', 'seem, shoulder, future', 'Implemented intermediate complexity', 'Smith-Bowen'),
(false, 1, 1, 'Will seven medical blood.', 'Fear police participant check several much single morning.', 'a, food, affect', 'Multi-lateral fault-tolerant encoding', 'Allen PLC'),
(false, 1, 1, 'Beat magazine attorney.', 'She campaign little near enter their institution.', 'deep, much, role', 'Exclusive transitional function', 'Carney-Santos'),
(false, 2, 3, 'Tonight later easy ask again.', 'Discover detail audience piece director town teacher.', 'audience, draw, protect', 'Extended needs-based capacity', 'Walls, Duncan and Kennedy'),
(false, 5, 1, 'Space couple best issue interest level.', 'Pull worker better.', 'I, fund, technology', 'Fully-configurable content-based core', 'West, Henderson and Ramirez'),
(false, 5, 1, 'Themselves away space task.', 'Anything yourself structure why.', 'unit, support, coach', 'Pre-emptive mission-critical data-warehouse', 'Barrera-Martin'),
(false, 5, 2, 'World enter six.', 'Expect recent room situation product main couple.', 'design, around, save', 'Centralized value-added functionalities', 'Williams Group'),
(false, 2, 2, 'Try most arm meet surface attention.', 'Push dog build three.', 'east, organization, people', 'Operative stable paradigm', 'Mills, Donovan and Harris'),
(false, 5, 2, 'Draw how public feel first.', 'Act perform none beyond.', 'Mrs, media, car', 'Monitored asymmetric encryption', 'Mitchell-Kim'),
(false, 1, 1, 'Region particularly would pressure account stage.', 'Use billion there enough threat.', 'score, choice, example', 'Expanded transitional Graphical User Interface', 'Watts LLC'),
(false, 4, 2, 'Major town suffer begin interest everybody.', 'Four capital woman.', 'claim, kind, relationship', 'Realigned 24/7 budgetary management', 'Landry Ltd'),
(false, 3, 1, 'Nation strong old.', 'Involve among half value.', 'win, always, group', 'Synergized dynamic secured line', 'Gomez PLC'),
(false, 2, 2, 'Wind see understand door class.', 'Thing agent say forward.', 'us, soon, ten', 'Fully-configurable encompassing complexity', 'Rodriguez, Brennan and Garrison'),
(false, 1, 1, 'Current truth glass star.', 'Development process huge everything attorney.', 'significant, go, meeting', 'Synergistic national groupware', 'Wilson LLC'),
(false, 4, 1, 'Oil worker although others.', 'Rock finish paper memory history office.', 'effort, remember, ability', 'Public-key systemic success', 'Mclaughlin, Gonzalez and Reynolds'),
(false, 3, 2, 'Perhaps professional by tonight medical.', 'For recent never court professor here.', 'security, community, notice', 'Open-architected neutral ability', 'Mitchell-Jordan'),
(false, 5, 2, 'Parent focus kid put memory soldier.', 'Probably exist professional people.', 'behavior, weight, dog', 'Integrated directional workforce', 'Hernandez Inc'),
(false, 1, 3, 'Worker particularly shoulder lay.', 'Offer responsibility himself hundred challenge reach throughout team.', 'those, sing, despite', 'Total multi-state Local Area Network', 'Grant Inc'),
(false, 4, 3, 'Card let most next fish.', 'Partner rest measure store natural today.', 'season, listen, else', 'Fully-configurable scalable focus group', 'Washington, Allen and Gonzales'),
(false, 1, 2, 'Doctor from throw ball.', 'Discuss really relationship ask.', 'imagine, my, indeed', 'Expanded intangible info-mediaries', 'Shah, Smith and Gilmore'),
(false, 1, 3, 'Herself accept goal send table well.', 'Mrs same son today major event.', 'magazine, home, protect', 'Open-architected uniform concept', 'Calhoun-Hooper'),
(false, 3, 3, 'Agree hour north agree poor career.', 'Consider employee force lawyer front they everything.', 'week, instead, strong', 'Phased 3rdgeneration synergy', 'Williams, Crane and Walker'),
(false, 5, 2, 'Sit prepare senior.', 'Current after charge call prove.', 'nor, design, record', 'Visionary holistic concept', 'Lawson, Adkins and Wilson'),
(false, 5, 1, 'Who blue agent find.', 'However resource away real physical big.', 'significant, sure, outside', 'Decentralized non-volatile toolset', 'Reed Group'),
(false, 1, 1, 'Attention positive actually information majority.', 'Whether player stock religious itself safe.', 'whole, establish, space', 'Public-key zero-defect matrices', 'Graham-Simon'),
(false, 2, 2, 'Focus early various everything.', 'During let particular her agreement surface consider.', 'deep, something, future', 'Right-sized tangible focus group', 'Smith, Vaughan and Miller'),
(false, 1, 1, 'Major serve real position make.', 'Behavior develop reality.', 'fill, ok, list', 'Progressive grid-enabled interface', 'Pierce, Bell and Chavez'),
(false, 1, 2, 'Edge building court build.', 'Week real course school everybody operation set.', 'others, wonder, strategy', 'Implemented discrete hierarchy', 'Turner Ltd'),
(false, 3, 2, 'Call animal approach factor want point.', 'Bill activity expect long future whole education.', 'technology, box, assume', 'Pre-emptive asynchronous orchestration', 'Parks, Hernandez and Shepherd'),
(false, 3, 1, 'Be easy newspaper indicate.', 'So difficult mission late kind team wrong figure.', 'perform, participant, science', 'Virtual demand-driven product', 'Baker Inc'),
(false, 3, 2, 'Dream necessary choose impact.', 'Like allow explain executive teacher author do enough.', 'social, operation, sound', 'Exclusive interactive budgetary management', 'Walker, Hernandez and Baker'),
(false, 2, 3, 'Author coach film.', 'Tv keep light fight I evening music.', 'just, our, threat', 'User-centric fresh-thinking portal', 'Johnson-Perez'),
(false, 3, 3, 'Onto again share start office several.', 'Like prepare trouble consider.', 'one, play, man', 'Cross-group methodical hardware', 'Cook-Santiago'),
(false, 1, 3, 'Form really explain war.', 'Already because education break significant ten stay.', 'ability, thank, left', 'Business-focused content-based model', 'Dean-Jimenez'),
(false, 2, 3, 'Service data near until just.', 'Building win participant dream citizen nearly need.', 'behavior, yeah, tree', 'Persistent bottom-line project', 'Jimenez Ltd'),
(false, 2, 1, 'Meeting event strong woman.', 'Lead certain course out second.', 'carry, attorney, significant', 'Operative global toolset', 'Adams, Smith and Barber'),
(false, 4, 2, 'Oil process tend land machine forward.', 'Help usually thank wonder draw him task.', 'improve, fish, list', 'Multi-tiered human-resource protocol', 'Pollard, Simpson and Johnson'),
(false, 3, 3, 'Whole forward beyond suddenly between treat.', 'Reveal improve pressure.', 'child, light, wide', 'Mandatory regional solution', 'Santos-Christian'),
(false, 5, 1, 'Here first responsibility service their along.', 'Doctor range explain dinner.', 'bed, within, set', 'Triple-buffered bandwidth-monitored intranet', 'Benson Inc'),
(false, 3, 1, 'Food argue grow.', 'Certainly most not society color bad.', 'that, people, drive', 'Reduced client-server emulation', 'Little-Stevens'),
(false, 2, 1, 'Together let explain.', 'Citizen kid generation onto police interesting economic.', 'suddenly, current, his', 'Polarized bi-directional encoding', 'Armstrong-Andrews'),
(false, 3, 2, 'Against stop how account.', 'Treat seat strategy.', 'total, simply, discover', 'Multi-channeled directional productivity', 'Oliver Ltd'),
(false, 3, 1, 'Pick tough position.', 'Small almost half capital travel.', 'force, indeed, customer', 'Quality-focused high-level moderator', 'Mcintyre, Rivas and Scott'),
(false, 2, 3, 'Whose far that sound life away.', 'Team right woman whose source.', 'hand, so, add', 'Public-key bottom-line knowledgebase', 'Chambers-Chambers'),
(false, 3, 1, 'Herself police he push likely people.', 'Foreign particular positive play less red power.', 'bring, animal, also', 'Proactive bifurcated attitude', 'Clay and Sons');